import { exercises } from "@/data/exercises";
const e = exercises.find((x) => x.slug === "leg-press-45")!;
console.log(JSON.stringify({ slug: e.slug, grupo: e.grupoMuscular, art: e.articulacaoPredominante, ativacao: e.ativacao.slice(0, 4) }, null, 1));
const m = new Set<string>();
for (const x of exercises) for (const a of x.ativacao) m.add(a.musculo);
console.log("musculos distintos:", m.size);
console.log([...m].sort().join(" | "));
const papeis = new Set<string>();
for (const x of exercises) for (const a of x.ativacao) papeis.add(a.papel);
console.log("papeis:", [...papeis].join(", "));
